module.exports = (function() {
var __MODS__ = {};
var __DEFINE__ = function(modId, func, req) { var m = { exports: {}, _tempexports: {} }; __MODS__[modId] = { status: 0, func: func, req: req, m: m }; };
var __REQUIRE__ = function(modId, source) { if(!__MODS__[modId]) return require(source); if(!__MODS__[modId].status) { var m = __MODS__[modId].m; m._exports = m._tempexports; var desp = Object.getOwnPropertyDescriptor(m, "exports"); if (desp && desp.configurable) Object.defineProperty(m, "exports", { set: function (val) { if(typeof val === "object" && val !== m._exports) { m._exports.__proto__ = val.__proto__; Object.keys(val).forEach(function (k) { m._exports[k] = val[k]; }); } m._tempexports = val }, get: function () { return m._tempexports; } }); __MODS__[modId].status = 1; __MODS__[modId].func(__MODS__[modId].req, m, m.exports); } return __MODS__[modId].m.exports; };
var __REQUIRE_WILDCARD__ = function(obj) { if(obj && obj.__esModule) { return obj; } else { var newObj = {}; if(obj != null) { for(var k in obj) { if (Object.prototype.hasOwnProperty.call(obj, k)) newObj[k] = obj[k]; } } newObj.default = obj; return newObj; } };
var __REQUIRE_DEFAULT__ = function(obj) { return obj && obj.__esModule ? obj.default : obj; };
__DEFINE__(1609375917881, function(require, module, exports) {
module.exports =require('./src/wxWOW')
}, function(modId) {var map = {"./src/wxWOW":1609375917882}; return __REQUIRE__(map[modId], modId); })
__DEFINE__(1609375917882, function(require, module, exports) {
function setWatcher(a){observe(a,"data",function(e,b,c){var d=this;if("data.wxwow"==e||this.data.$fv_wxWoWDataObserved)return 0;setTimeout(function(){ScrollFunc(d)},200)},!0,a,"data")}function observe(a,e,b,c,d,h){var f=a[e];c&&null!=f&&"object"===typeof f&&Object.keys(f).forEach(function(g){"__webviewId__"!=g&&"Object"!=g&&"$fv_wxWoWDataObserve"!=g&&"$fv_wxWoW"!=g&&observe(f,g,b,c,d,h+"."+g)});Object.defineProperty(a,e,{configurable:!0,enumerable:!0,set:function(g){b.call(d,h,g,f);f=g;c&&null!=f&&"object"===typeof f&&observe(a,e,b,c,d,h)},get:function(){return f}})}var ScrollFunc=function(a){wx.createSelectorQuery().selectAll(".wx-wow").boundingClientRect(".wx-wow").exec(function(e){"object"==typeof e[0]&&e[0].forEach(function(b){var c=b.dataset.wxWowId,d=b.dataset.wxWowOffset?parseInt(b.dataset.wxWowOffset):.15*a.data.$fv_wxwowHeight;a.data.$fv_wxwowHeight-d>b.top&&-1==a.data.$fv_wxWoW.oldlist.indexOf(c)&&(a.data.$fv_wxWoW.oldlist.push(c),a.data.$fv_wxWoWDataObserved?"":a.setData({$fv_wxWoWDataObserved:!0}),a.data.wxwow={idx:".wowId-"+c,prefix:"animated",delayTime:b.dataset.wxWowDelay?b.dataset.wxWowDelay:"",durationTime:b.dataset.wxWowDuration?b.dataset.wxWowDuration:"",iteration:b.dataset.wxWowIteration?b.dataset.wxWowIteration:""},a.setData({wxwow:a.data.wxwow}))})})},$FV_WXWOW={OnLoadFunc:function(a){var e=this;wx.getSystemInfo({success:function(b){e.setData({$fv_wxwowHeight:b.screenHeight,$fv_wxwowWidth:b.screenWidth,$fv_wxWoWDataObserve:null,$fv_wxWoWDataObserved:!1,$fv_wxWoW:{oldlist:[]},wxwow:{}});setWatcher(e)}})},OnShowFunc:function(a){},OnPageScrollFunc:function(a){ScrollFunc(this)}},$fv_wowPage=Page;module.exports=function(a){var e=a.onPageScroll,b=a.onShow;a.onLoad=function(c){return function(d){"function"==typeof $FV_WXWOW.OnLoadFunc&&$FV_WXWOW.OnLoadFunc.call(this,d);c&&c.call(this,d)}}(a.onLoad);a.onShow=function(c){return function(d){"function"==typeof $FV_WXWOW.OnShowFunc&&$FV_WXWOW.OnShowFunc.call(this,d);c&&c.call(this,d)}}(b);a.onPageScroll=function(c){return function(d){"function"==typeof $FV_WXWOW.OnPageScrollFunc&&$FV_WXWOW.OnPageScrollFunc.call(this,d.scrollTop);c&&c.call(this,d)}}(e);return $fv_wowPage.call(this,a)};
}, function(modId) { var map = {}; return __REQUIRE__(map[modId], modId); })
return __REQUIRE__(1609375917881);
})()
//# sourceMappingURL=index.js.map